# Generated by Django 4.1.4 on 2023-01-05 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0004_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='program',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_num',
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('day_type', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_days', to='iron_app.program')),
            ],
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('program', 'day'), name='unique_program_day'),
        ),
    ]
