# Generated by Django 4.1.4 on 2023-01-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0005_remove_workout_program_remove_workout_workout_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='program_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='iron_app.programday'),
            preserve_default=False,
        ),
    ]
