# Generated by Django 4.1.4 on 2023-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0006_workout_program_day'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_program'),
        ),
    ]
