# Generated by Django 4.1.4 on 2023-02-20 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0014_alter_setschema_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
