# Generated by Django 4.1.4 on 2023-02-22 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0016_alter_set_number_set_unique_set_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='is_distance',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_time',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_weight',
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
