# Generated by Django 4.1.4 on 2023-02-24 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0017_remove_exercise_is_distance_remove_exercise_is_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
