# Generated by Django 4.1.4 on 2023-02-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0018_exercise_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('section', 'number'), name='unique_exercise_number'),
        ),
    ]
