# Generated by Django 4.1.4 on 2023-02-24 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0019_exercise_unique_exercise_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
