# Generated by Django 4.1.4 on 2023-02-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_app', '0022_section_unique_section_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisebase',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
